colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
# 允許程式碼區塊複製按鈕
enableCodeCopy = true
replyByEmail = false
mainSections = [ "posts", "journals" ]
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/featured.svg"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true
firebase = { }
fathomAnalytics = { }
verification = { }

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

# 首頁設定
[homepage]
# hero 背景圖片寬度等長於 Recent 項目圖片寬度
# background 背景圖片寬度等長於螢幕寬度
layout = "hero" # valid options: page, profile, hero, card, background, custom
# 顯示最近的文章
showRecent = true
# 最近的文章顯示幾個
showRecentItems = 6
# 是否顯示更多連結
showMoreLink = false
# showMoreLinkDest = "/posts"
# 以卡片庫的形式顯示最近的文章
cardView = false
# 文章卡片庫的寬度以佔據可用的全部寬度。
cardViewScreenWidth = false
# 使主頁佈局中的背景圖像隨著滾動而變得模糊
layoutBackgroundBlur = false

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = false
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
showSummary = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

# 分類法
[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = false
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false

[buymeacoffee]
identifier = "ben199810"
globalWidget = true
globalWidgetMessage = ""
globalWidgetColor = "#FFDD00"
globalWidgetPosition = "Right"
